### ISSUE TITLE
Save the project in Json format

### ISSUE THREAD

**Issue by vonfritz** [ooflet/Mi-Create#11]
save the project in Json format

It would be useful to be able to save the project in Json format to be able to use it with the Chinese GMF Packer/Compiler.
Currently it is necessary to manually convert the XML file to Json and then adapt it to the required format of the Chinese packer.

**Comment by ooflet** [comment]
Is the Json project just the S3/MB9Pro format? If not, can you attach an example json project so I know what im working with?

**Comment by vonfritz** [comment]
randomly chosen from the examples folder.
[wfDef.json](https://github.com/ooflet/Mi-Create/files/15168970/wfDef.json)

**Comment by Chriz76** [comment]
@ooflet where can I get the chinese compiler?

**Comment by vonfritz** [comment]
> @vonfritz where can I get the chinese compiler?
https://www.bandbbs.cn/threads/7748/

**Comment by ooflet** [comment]
added in GMF/json support branch [GMF-format-support-(json)](https://github.com/ooflet/Mi-Create/tree/GMF-format-support-(json))
