### ISSUE TITLE
New Project keeps crashing in Windows

### ISSUE THREAD

**Issue by sgupta999** [ooflet/Mi-Create#14]
**Describe the bug**
Installed the latest v3 beta from releases on widows 11 pro 64 bit
Run the app as administrator
Trying to create a new project for Redmi Watch 3 active
Select destination folder
When i hit ok the app just crashed.
I don't see a log file so i do not know why it is crashing

**To Reproduce**

**Expected behavior**
expected to create a new project

**Screenshots**
![image](https://github.com/ooflet/Mi-Create/assets/35128032/a026c4a0-611a-490d-b32d-7bd4ccc5e481)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 11 pro

**Additional context**

**Comment by ooflet** [comment]
I am unable to replicate, can you try a different project location? If that fails, can you see if it still fails on the latest build of Mi Create and if so send the error message that is displayed on the command prompt?

To run latest build you can preferably follow instructions on README.md for running on source or use the pre-compiled version at https://drive.google.com/file/d/1OagmLnWuOtO6Qr5weYuA3GP2HcmDEdbA/view

**Comment by sgupta999** [comment]
Thank you for your prompt reply.
I copied this pre-compiled version on the current install directory.
Was finally able to create a new project.

Now to figure out how to decompile an existing watch face and use that as an existing project starting point.
And how to package and upload a new created watchfact to my redmi watch.

Are there any wikis/directions for that?
if there's a process to be followed but not currently i can help document so you update the wiki?

thx so much

**Comment by ooflet** [comment]
Mi Create comes bundled with a decompiler that is currenrly not implemented in UI. It is located in the compiler folder in the install directory (unpack.exe). It is not perfect, especially for some stock Xiaomi watchfaces. The decompiler decompiles to the current working directory, there is no argument to specify where to unpack. You can simply just drag and drop   a compiled watchface binary on top of the executable and have it unpack there

There is a wiki with steps on how to compile and publish the watchface (onto m0tral's servers) at https://ooflet.github.io/docs/quickstart/intro/
