### ISSUE TITLE
Local test watchface

### ISSUE THREAD

**Issue by FRIKIdelTO** [ooflet/Mi-Create#16]
Is there any way to local test my custom watchface on my device Redmi Active 3? I have a rooted android smartphone with custom Myfitness apk installed

**Comment by vonfritz** [comment]
You can try using the notify for Xiaomi application but I'm not sure if your watch model is fully supported. Also be careful the compiler support for your model is very recent and not yet 100 percent.

**Comment by ooflet** [comment]
If you're running v0.3, that release is already quite old and no longer has the latest compiler. If you're making a watchface for Redmi Watch 3 Active I'd suggest you either use EasyFace for now, or if you're fine with bugs you can test the latest testing version by running source code which has the new compiler.

**Comment by ooflet** [comment]
There's also nothing stopping you from manually replacing the latest compiler and DeviceInfo.db from EasyFace to Mi Create's program files, but for now simply using EasyFace would be the best option for you.
