### ISSUE TITLE
Unable to compile or save the project

### ISSUE THREAD

**Issue by alan7383** [ooflet/Mi-Create#21]
An error message appears when I try to compile my project. Any ideas?

I have to go to the console icon, it tells me to save, I click yes, and then the error message appears. Mi Create closes right after. 
![image](https://github.com/user-attachments/assets/c85468f4-a49d-469b-b7a9-acad6ca72689)

**Comment by ooflet** [comment]
Could you send me just your .fprj file and reinstall Mi Create? There was an issue with the original installer that I have already updated. I'll send you a fixed version of the .fprj file that should be able to compile.

**Comment by alan7383** [comment]
[ÄÍ¿ËV1.zip](https://github.com/user-attachments/files/16424650/AI.EV1.zip)

Here is my project, I also reinstalled Mi Create but I still end up getting the same error...

**Comment by ooflet** [comment]
Fixed, install Mi Create v1.0.1 https://github.com/ooflet/Mi-Create/releases/tag/v1.0.1

Also your project has a stray empty image in the ImageList object which will error compilation. Replace the fprj file with the following txt file if you did not intend for this to happen (github does not allow other file types).
[fprj.txt](https://github.com/user-attachments/files/16425520/fprj.txt)

**Comment by alan7383** [comment]
Oh! Great for the fix, in fact my imagelist was empty because I had not yet finished my project
