### ISSUE TITLE
Is it possible to use a gif or a video?

### ISSUE THREAD

**Issue by DefaultIvanAdrey** [ooflet/Mi-Create#25]
I want to find a way to use this.

RE7 Codex Watchface

![undefined - Imgur](https://github.com/user-attachments/assets/f134cb7d-32ee-4f99-b4dc-552e86f699c4)

**Comment by ooflet** [comment]
Follow the instructions on https://github.com/m0tral/EasyFace/wiki/Animations, you also need to split the animation into frames. I'd suggest cropping out static parts of the gif and only having the pulse animation because large animations lag the watch and increase the watchface's size.
