### ISSUE TITLE
Default index did not work

### ISSUE THREAD

**Issue by DieMetRik** [ooflet/Mi-Create#29]
First of ALL. Nice program. Thanks for your job!

**Describe the bug**
ImageList -> Default index is not working and has a limit of 99

Mi Crate 1.0.1 with EasyFace 4.15 compiler

**To Reproduce**
1. Go to ImageList ->Default index
2. Try to enter any number
3. And nothing 

See scrennshot:
![Screenshot 2024-09-22 152600](https://github.com/user-attachments/assets/5bcd4582-2407-45d3-b78f-f1a2fe6d0a23)

**Comment by ooflet** [comment]
Fixed, will be released on 1.1, otherwise you can run from source code.

**Comment by DieMetRik** [comment]
If i use steps to km, in this case Default number may be >10000. 

In your fix max number 999. 
Pls adjust max to 20000

**Comment by ooflet** [comment]
I see, thank you for the correction. I've set it so that there is no limit (except max signed int32 value)
