### ISSUE TITLE
Mi Band 8: Visibility Trigger not working

### ISSUE THREAD

**Issue by bebbo203** [ooflet/Mi-Create#3]
It look like that visibiliy triggers are not working and the images are always showing.
I specifically tried "Sleep status" and while a simple digital number widget would change according to the value (0 when ND is not active, 1 otherwise) the trigger would not hide an image widget

**Comment by ooflet** [comment]
Seems like either a compiler issue or an issue with the Mi Band 8 itself. I do not maintain the compiler, please contact @m0tral on telegram

**Comment by m0tral** [comment]
visibility by source doesn't work on this type of Xiaomi models, it works on Mi Watch, Mi Color only,
@ooflet if you have in UI remove this field
