### ISSUE TITLE
XML Document Error

### ISSUE THREAD

**Issue by ESLGameDev** [ooflet/Mi-Create#33]
**Describe the bug**
When i try to compile, the program gives the error "Failed to build watchface! XML Document Error (7, 255)".
I then tried to manually edit the fprj file and take a look at it, but everything seems fine, i don't see any error.

**To Reproduce**
1. Open Mi Create
2. Open project
3. Try to compile project

**Expected behavior**
The project should be compiled without errors

**Troubleshooting**
- Log File: 
[app.log](https://github.com/user-attachments/files/17485945/app.log)

- Project: 
[shrek.zip](https://github.com/user-attachments/files/17485958/shrek.zip)

**Screenshots**

![Captura de tela 2024-10-23 061152](https://github.com/user-attachments/assets/0895ad68-ec27-45eb-a6a7-f816b0445971)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Mi Create 1.0.1

**Comment by vonfritz** [comment]
The erro is in the generated XML file shrek.fprj 
Visible_Src="None" should be Visible_Src="0"

Then you have others errors like
Error in imageList: doisponto.png images in list must have the same width
in the "month" widget.

**Comment by ESLGameDev** [comment]
> The erro is in the generated XML file shrek.fprj Visible_Src="None" should be Visible_Src="0"
> 
> Then you have others errors like Error in imageList: doisponto.png images in list must have the same width in the "month" widget.

Thanks, now it works and has compiled without problems :)
