### ISSUE TITLE
[Build error] OpenBlob/3315

### ISSUE THREAD

**Issue by guillaumegarcia13** [ooflet/Mi-Create#38]
**Describe the bug**
When building, an error ocurred: "Failed to build watchface! Error: unable to open image 'C:\Code\mi-band9-hrc\mi-band9-hrc\images\': No such file or directory @ error/blob.c/OpenBlob/3315"

**To Reproduce**
1. Create a new project
2. Add a couple of widget (hour, minute) as digital number
3. Set project name and thumbnail
4. Build
5. See error

**Expected behavior**
Build completes

**Troubleshooting**
- Log File/Error Message: [on Windows, log file is located at C:\Users\{username}\AppData\Local\Programs\Mi Create\data\app.log]
- .fprj file

**Screenshots**
![image](https://github.com/user-attachments/assets/dc6933ac-58a5-4454-ac18-74e91e4cf188)

**Desktop (please complete the following information):**
 - Windows 11
 - Mi'Create v1.0.1

**Comment by ooflet** [comment]
@Rosabis Make sure all widgets have images set correctly, this error appears when the image property in a widget is set to nothing or an image that does not exist.
