### ISSUE TITLE
Unable to create analogClock - TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

### ISSUE THREAD

**Issue by gab51299** [ooflet/Mi-Create#40]
Created a basic watchface for the Mi Band 9 from scratch and build was successful. Watchface contains a simple analog clock, and a digital number showing the Date today:

![image_2024-11-13_001801083](https://github.com/user-attachments/assets/d2f63cde-f10f-4b2b-b992-0c04b02fc41e)

Wanted to double check by running it through the unpacker and opening the project again, was greeted with the following error when opening the .fprj file:

> Cannot render project! Unable to create object analogClock_00:
 Traceback (most recent call last):
  File "C:\PROGRA~1\MICREA~1\widgets\canvas.py", line 440, in createWidgetFromData
  File "C:\PROGRA~1\MICREA~1\widgets\canvas.py", line 331, in createAnalogDisplay
  File "C:\PROGRA~1\MICREA~1\ntpath.py", line 149, in join
  File "C:\PROGRA~1\MICREA~1\genericpath.py", line 164, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

**Comment by ooflet** [comment]
Could you send the .fprj file of the unpacked project?

**Comment by gab51299** [comment]
[Hermes V3 Unpacked.zip](https://github.com/user-attachments/files/17725381/Hermes.V3.Unpacked.zip)

Here's the zip of the unpacked .fprj

**Comment by ooflet** [comment]
It's been fixed on the main branch of Mi Create (commit 58297f453d20288530dd0808d55a1d32ef1707d8), try running the source code.
