### ISSUE TITLE
Watchface images changed Hue? Different color appears when unpacked

### ISSUE THREAD

**Issue by gab51299** [ooflet/Mi-Create#41]
**Describe the bug**
After unpacking the .face file, all images are a different color; the hue shifted by about 180?

**To Reproduce**
1. Create watch face:
- Background Image
- 4 Digital Numbers (for appearance and formatting purposes), displays time (2 hour digits and 2 min digits)
3. Build Watchface
4. Unpack Watchface 
5. See images

**Expected behavior**
Normal watchface with unchanged colors

**Troubleshooting**
- No error logs

**Screenshots**
![image_2024-11-13_003339257](https://github.com/user-attachments/assets/e591dbb4-30e2-42f0-90dd-378828f06fbe)
![image](https://github.com/user-attachments/assets/1ec5254a-0c1d-46f2-bf7c-4ce782059600)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by ooflet** [comment]
Redmi Watch 2 lite has a few issues, the compiler dev hasn't seemed to have fixed the issue for more than a year now so I'd suggest you try using Mino's miwtool (https://github.com/Mino260806/miwtool) where your (issue)[https://github.com/Mino260806/miwtool/issues/2] seems to have been fixed. Do note that the project format is different when using miwtool.
