### ISSUE TITLE
Linux Compiler not ready, when ?

### ISSUE THREAD

**Issue by zz64** [ooflet/Mi-Create#46]
Hi, 

running successfully in GNU/Linux, but i can't compile project.

 ![20241128_18-21-53](https://github.com/user-attachments/assets/54a5048e-b15c-448b-be9f-a3ad00db010a)

Thanks for your good Work :-)

**Comment by ooflet** [comment]
I don't maintain the compiler, and it is not open source. I have contacted the dev to provide linux builds of his compiler as well, he has accepted but no builds are available so far. Wine also runs the compiler binary perfectly.

So far I am only waiting for the native build of the compiler to linux, but if this were not to happen I will likely implement the binary using wine/mono.

**Comment by vonfritz** [comment]
You can use wine to compile using the command line like this:

wine compiler.exe -b ./yourproject.fprj output 123456

123456 is the watchface ID which is not considered by the compiler but you still have to specify it otherwise it gives you an error.

**Comment by ooflet** [comment]
To keep everything simple for now, I have added Linux support onto the experimental GMF branch if you want to test it out https://github.com/ooflet/Mi-Create/tree/GMF-format-support-(json), however the branch is quite unstable and not ready for production yet. There are some other features on there that are not in the main branch yet.
