### ISSUE TITLE
Add support for mi band 9 pro

### ISSUE THREAD

**Issue by Jbcbro** [ooflet/Mi-Create#47]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vonfritz** [comment]
the graphic resolution of the mi band 9 Pro is the same as the mi band 8 Pro 336 * 480 so in my opinion you can use the settings of the 8 Pro to try to make a simple watch face and upload it should work.

**Comment by ooflet** [comment]
Added in 7c67e6fc5fe282d1882179301a6029db6bfb44d7, if you want to update v1.0.1 with Mi Band 9 Pro support download the latest version of EasyFace and update the data files through settings > 3 dots menu > Update Compiler from EasyFace
