### ISSUE TITLE
 error/blob.c/OpenBlob/3315

### ISSUE THREAD

**Issue by muratishik** [ooflet/Mi-Create#48]
When I try to build, I get the error @ error/blob.c/OpenBlob/3315. Can you help me?

![Ekran Görüntüsü (40)](https://github.com/user-attachments/assets/5e5851aa-98bc-4458-a1c9-19f466e94591)

**Comment by ooflet** [comment]
You likely have an empty image property, can you send your project?

**Comment by muratishik** [comment]
[face2.zip](https://github.com/user-attachments/files/18160858/face2.zip)

thanks for your supports

**Comment by ooflet** [comment]
Yep, you need to fill out the Negative Sign property with an image. You can just use the image you use for 0, the negative sign property represents either a negative number with weather or when data is not available. You do not need to make a negative sign image unless you're using the property for data sources like weather

**Comment by muratishik** [comment]
It worked, thanks. It only gave the output as .face extension, I couldn't convert it to .bin, probably shown in the documentation.

Thanks again

**Comment by ooflet** [comment]
The .face file is your .bin, rename the extension to .bin.
