### ISSUE TITLE
Adding Image widget on new project makes application crash

### ISSUE THREAD

**Issue by vonfritz** [ooflet/Mi-Create#5]
the problem occurs with the last 2 revisions on the Linux operating system. The application closes when you add a widget by clicking on the + sign and selecting any widget.

Starting app from terminal ends up with this error:

Traceback (most recent call last):
  File "/RW4/Mi-Create/src/utils/history.py", line 17, in redo
    self.commandFunc("redo", self.objectIndex, self.objectData)
  File "/RW4/./Mi-Create/src/main.py", line 726, in commandFunc
    currentProject["data"]["FaceProject"]["Screen"]["Widget"][key] = object
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: list indices must be integers or slices, not str

Add any other context about the problem here.

**Comment by ooflet** [comment]
Fixed on latest revision
