### ISSUE TITLE
ImportError : watchData

### ISSUE THREAD

**Issue by vonfritz** [ooflet/Mi-Create#7]
Hi
After latest update : ImportError: cannot import name 'watchData'

in src/widgets/canvas.py there is a typo it should be uppercase.
after fixing this it throws another error : AttributeError: 'MainWindow' object has no attribute 'openNewFormatProject'

**Comment by ooflet** [comment]
Known issue, I'm moving over to a new watchface project management system and I have yet to commit because it is still not finished and unstable.

**Comment by vonfritz** [comment]
Ok, why not using another branch for this?
As it is master is broken.

**Comment by ooflet** [comment]
Honestly I haven't bothered setting up branches for github, i'll do that now.
