### ISSUE TITLE
Decimal point in digital numbers

### ISSUE THREAD

**Issue by vonfritz** [ooflet/Mi-Create#9]
In some cases (Distance travelled) you have the possibility to display the decimals.
To do this you need to add on 11 digital numbers of which the eleventh is the point and set the digits to 20.
Currently only possible by manually editing the XML file.
It would be nice if this feature could be implemented

**Comment by Chriz76** [comment]
@vonfritz thank you. How did you find this solution? Is there some kind of spec document and maybe more options?

**Comment by vonfritz** [comment]
> @vonfritz thank you. How did you find this solution? Is there some kind of spec document and maybe more options?

I've read it in some place that I can't remember now. No documentation. If you put 30 or 40 digits it should display the smaller unit, you have to try.

**Comment by vonfritz** [comment]
Hi
@ooflet Have you tested your solution?
does not work for me sorry.

**Comment by ooflet** [comment]
Could you provide a .fprj file with a working example of decimal numbers to compare?

**Comment by vonfritz** [comment]
I attach a simple "Hack" patch to be able to use your application to do decimals and a complete working compiled example for the S3.
[example.tar.gz](https://github.com/user-attachments/files/16473680/example.tar.gz)
[diff.patch.gz](https://github.com/user-attachments/files/16473692/diff.patch.gz)

**Comment by ooflet** [comment]
Ah I see, I misunderstood it sorry. I've applied your patch for now, will work on a better solution 🙂
